### ISSUE TITLE
About Pagination

### ISSUE THREAD

**Issue by chayancbnits** [oxyii/react-native-web-swiper#16]
Thanks for supporting me , I have another question for Pagination, Could tell you tell me how to get item by Pagination ?

**Comment by oxyii** [comment]
@chayancbnits Pagination? You mean [manual triggering](https://github.com/oxyii/react-native-web-swiper#interaction-methods) slides changing? Or custom numeric dots? If custom dots then you must implement `DotComponent` prop. Something like this:

```jsx
<Swiper
  controlsProps={{
    dotsTouchable: true, // <- pass onPress prop func to your DotComponent ?
    DotComponent: ({ onPress, index, isActive }) => (
      <Text style={isActive ? styles.activeDot : styles.dot} onPress={onPress}>
        {index+1}
      </Text>
    ),
  }}
>
  <View slide1 />
  <View slide2 />
</Swiper>
```

and if manual triggering:

```jsx
export default SomeComponentClass extends React.Component {
  swiperRef;

  render() {
    return (
      <View>
        <Swiper ref={swiperInstance => this.swiperRef = swiperInstance}>
          <View slide1 />
          <View slide2 />
          <View slide3 />
        </Swiper>
        <Button
          onPress={() => this.swiperRef && this.swiperRef.goTo(2)}
          title="go to third"
        />
      </View>
    );
  }
}
```

**Comment by chayancbnits** [comment]
Pagination is the process of separating print or digital content into discrete pages. For print documents and some online content, pagination also refers to the automated process of adding consecutive numbers to identify the sequential order of pages.

For example I have total 50 items, At first time I have to show 10 items show for swipe , when I have to swiped each items, when I have swipe 9th number item for show 10th number item and as well as a rest API call for next 11 to 20 item get from sever and appended previous items.

![1_6727j2BrMrfiAqdzSEezdg](https://user-images.githubusercontent.com/51107138/63217282-44b1c400-c161-11e9-9113-2646b7e75189.gif)

**Comment by oxyii** [comment]
@chayancbnits sorry but this swiper is not suitable for your tasks. And lazy loading is not planned at all because it will entail a whole set of functionality and a lot of errors that are so far from the functionality of the swiper. E.g. including [`VirtualizedList`](https://facebook.github.io/react-native/docs/virtualizedlist). Without it, loading will be slower with each iteration... I am not ready to support all this )))
You can use RN components such a [`FlatList`](https://facebook.github.io/react-native/docs/flatlist.html) and [adjust](https://facebook.github.io/react-native/docs/flatlist#scrolltoindex) the scroll position based on touch events. [`ScrollView` props](https://facebook.github.io/react-native/docs/scrollview#props) already built in FlatList. So you can try to use ScrollView's touches props inside FlatList. [leecade's `react-native-swiper` src](https://github.com/leecade/react-native-swiper/blob/master/src/index.js#L777-L789) can helps.
